spring.application.name=realtime-sync-engine

# Server
server.port=8080

# Database - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sync_engine?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=8309612874
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mySuperSecretKeyThatIsAtLeast64CharactersLongForHS512AlgorithmUsedForJWT
jwt.expiration=604800000

# Debezium CDC — disabled by default
debezium.enabled=false

# Disable RabbitMQ auto-configuration (optional service)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.sync.engine=DEBUG